scanner:
  name: "Leica RTC360"
  typical_noise: 0.002  # 2mm at 10m
  max_range: 130.0      # meters
  angular_resolution: 0.009  # degrees
  intensity_range: [0, 2048]

cleaning:
  statistical_outlier:
    neighbors: 30
    std_ratio: 1.5
  radius_outlier:
    radius: 0.05  # 5cm
    min_neighbors: 10

thinning:
  method: "voxel"
  voxel_size: 0.01  # 1cm for architectural scans
  preserve_boundaries: true

reflection:
  intensity_available: true
  intensity_threshold: 0.95
  glass_detection: true
  clustering_epsilon: 0.02